### ISSUE TITLE
Speedup Tsung starting when using hundreds of clients

### ISSUE THREAD

**Issue by nniclausse** [processone/tsung#137]
Currently, Tsung starts at most 10 remote beams with ssh in parallel. This can be  slow if it has to start hundreds of beams on several hosts.

**Comment by tisba** [comment]
Wow, this is awesome! A while back I was thinking about how to improve this without making to much changes, but this approach seems to be simple and straight forward. Thanks!

**Comment by nniclausse** [comment]
i was thinking about your use case , when i realize that it was silly to not spread the list of beams, and by doing this we could go much higher that the 10 parallel start. 
I did a test with 620 beams (on ~50 nodes), it tooks 1mn28s (and most of the time is spent in the global sync phase, so there is still room to optimize it further)

**Comment by tisba** [comment]
I started to work on researching what is necessary to use `-connect_all false` in tsung and only establish explicit connections between controllers and slaves and not between slaves. It's a bit tricky, because global name registration does not work in that case, but that should not technical not be necessary. It does require a bit of rework though.

If we can get this done, there will only be one connection per slave, and not `(slave^2-slave)/2` connections.
