### ISSUE TITLE
How can i use dynamic vars with the attribute value of eq?

### ISSUE THREAD

**Issue by alicehanhy** [processone/tsung#168]
Hi,
I'm a tester,i use tsung to test server.
The scenario is :
client send login request with username read from enc.csv,get the userid from the response compare with the userid read from the enc.csv,as the username matched the userid,so i check if the value respond from server equals  userid read from enc.csv 
this is my script:

```xml
<options>
   <option name="file_server" id="userdb" value="/usr/local/tsung6/hanhy/login/case1/enc.csv"></option>
</options>

<sessions>
 <session probability="100" name="raw" type="ts_raw">
   <setdynvars sourcetype="file" fileid="userdb" delimiter="," order="iter">
     <var name="userid"/>
     <var name="username"/>
   </setdynvars>
    <transaction name="data">
       <request subst="true">
         <dyn_variable name="loginTag" re="&lt;success xmlns=&quot;urn:ietf:params:xml:ns:xmpp-sasl&quot;&gt;(.*)@im.ebnew.com/Tsung&lt;/success&gt;"/>
         <raw data="&lt;auth xmlns=&quot;urn:ietf:params:xml:ns:xmpp-sasl&quot; resource=&quot;Tsung&quot;&gt;%%_username%%&lt;/auth&gt;" ack="local"></raw>
       </request>
    </transaction>
    <thinktime value="4"/>
    <transaction name="close">
        <if var="loginTag" eq="userid">
        <request>
         <raw data="stopstopstop" ack="local"></raw</request>
        </if>
    </transaction>
  </session>
 </sessions>
```

when i use if element,i want to set the attribute value of the eq as a dynamic value,but set the attribute value as :
 <if var="loginTag" eq="userid">
dynamic variable "loginTag" is replaced ,but "userid" isn't replaced.
However in Tsung ,if i want to get the dyn_variables,i have to use it like this:
```xml
<request subst="true">
  <http url="/go.cgi" version="1.0"
    contents="username=nic&amp;random_num=%%_random_num%%&amp;op=login"
    content_type="application/x-www-form-urlencoded" method="POST">
  </http>
</request>
```
But the if tag does't have the attribute "subst=true".
Now,does eq attribute support dynamic variable in the if tag? or i use it in a wrong way?

**Comment by tisba** [comment]
As far as I can tell, the value is currently not substituted.

However it's a bit hard to fully understand your problem. Could you please surround your XML configuration using \`\`\` (code blocks)? And I'd appreachiate it if you could format your XML a little bit to make it easier to read :)

**Comment by alicehanhy** [comment]
Ok,thank you.
```
<options>
 <option name="file_server" id="userdb" value="/usr/local/tsung6/hanhy/login/case1/enc.csv"></option> 
</options>

<sessions> 
<session probability="100" name="raw" type="ts_raw"> 
<setdynvars sourcetype="file" fileid="userdb" delimiter="," order="iter"> 
 <var name="userid"/> 
 <var name="username"/>
 </setdynvars>
 <transaction name="data">
 <request subst="true"> 
 <dyn_variable name="loginTag" re="&lt;success xmlns=&quot;urn:ietf:params:xml:ns:xmpp-sasl&quot;&gt;(.*)@im.ebnew.com/Tsung&lt;/success&gt;"/>
  <raw data="&lt;auth xmlns=&quot;urn:ietf:params:xml:ns:xmpp-sasl&quot; resource=&quot;Tsung&quot;&gt;%%_username%%&lt;/auth&gt;" ack="local"></raw> 
</request> 
</transaction>
<thinktime value="4"/>
<transaction name="close">
<if var="loginTag" eq="userid">
<request> 
 <raw data="stopstopstop" ack="local"></raw> 
</request> 
</if> 
</transaction> 
</session> 
</sessions> 
```

**Comment by bltb** [comment]
I think the DSL does not support (yet) dynamic variable expansion in the flow control blocks such as `if`.

If you really need this now you could... 

```
<setdynvars sourcetype="eval"
            code="fun({Pid,DynVars})->
                      {ok,Val1}=ts_dynvars:lookup(loginTag,DynVars),
                      {ok,Val2}=ts_dynvars:lookup(userid,DynVars),
                       Val1 =:= Val2 end.">
  <var name="is_expected_userid" />
</setdynvars>

<transaction name="close">
 <if var="is_expected_userid" eq="true">
 <request>
  <raw data="stopstopstop" ack="local"></raw>
 </request>
 </if>
</transaction>

```

**Comment by bltb** [comment]
Could we close this?

Or maybe tag this as an enhancement?

Ok,thank you.

<options>
 <option name="file_server" id="userdb"
value="/usr/local/tsung6/hanhy/login/case1/enc.csv"></option>
</options>

<sessions>
<session probability="100" name="raw" type="ts_raw">
<setdynvars sourcetype="file" fileid="userdb" delimiter="," order="iter">
 <var name="userid"/>
 <var name="username"/>
 </setdynvars>
 <transaction name="data">
 <request subst="true">
 <dyn_variable name="loginTag" re="&lt;success
xmlns=&quot;urn:ietf:params:xml:ns:xmpp-sasl&quot;&gt;(.*)@im.ebnew.com/Tsung&lt;/success&gt;"/>
  <raw data="&lt;auth
xmlns=&quot;urn:ietf:params:xml:ns:xmpp-sasl&quot;
resource=&quot;Tsung&quot;&gt;%%_username%%&lt;/auth&gt;"
ack="local"></raw>
</request>
</transaction>
<thinktime value="4"/>
<transaction name="close">
<if var="loginTag" eq="userid">
<request>
 <raw data="stopstopstop" ack="local"></raw>
</request>
</if>
</transaction>
</session>
</sessions>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/processone/tsung/issues/168#issuecomment-216763006>

**Comment by alicehanhy** [comment]
Ok,thank you

**Comment by alicehanhy** [comment]
Ok

**Comment by tisba** [comment]
IMO the `value` part of `<if>` should support substitution.

Adding this should be fairly simple. Code to take a look at is this: 
https://github.com/processone/tsung/blob/fbd11cb5ad6eb3ba4491a3ad08d72a734d821a1a/src/tsung/ts_client.erl#L646-L656

`Value` needs to be processed via `ts_search:subst`. This way it may contain placeholders like `foo-%%_userid%%`.
