### ISSUE TITLE
Graphs show no data

### ISSUE THREAD

**Issue by sschneider1207** [processone/tsung#256]
I ran a 12 hour test and I'm unable to view any graphs for the recorded stats.  The dashboard times out with a 504 and `tsung_stats.pl` (with dygraph option) generates blank graphs.  If I had to guess I'd say this is because there are too many data points?

Attached is the full tsung log directory with generated reports:
[20170911.tar.gz](https://github.com/processone/tsung/files/1296017/20170911.tar.gz)

**Comment by sschneider1207** [comment]
Decided to open up the console and the issue actually looks to be:
```
XMLHttpRequest cannot load file:///.../csv_data/graphes-HTTP_CODE-rate.csv. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```
for every csv file

**Comment by tisba** [comment]
That is because modern browsers won't load stuff from `file://`. You can either fire up a web server to view your reports, or use the `tsung view` option. This will start only the report web server from tsung.

To start a simple web server, you can do

```console
ruby -run -e httpd . -p 9090
```
or
```console
python -m SimpleHTTPServer 9090
```

Using this, your reports just work fine:

<img width="1329" alt="screen shot 2018-06-02 at 13 28 58" src="https://user-images.githubusercontent.com/75156/40873910-f5414e26-6668-11e8-8932-38e7c598d13d.png">

An alternative is to generate the reports without the `--dygraph` option. This will generate PNG images which should be able to be loaded by Chrome just fine.
